language: c
script: make check COVERAGE=1
compiler:
  - clang
  - gcc
python:
  - "2.7"
install:
  - pip install --user urllib3[secure] cpp-coveralls
after_success:
  - coveralls --gcov-options '\-lp' -i $PWD/shellhop.c
